security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        # ← AJOUT : Login en premier, sans JWT
        public_api:
            pattern: ^/api/(login|register|forgot-password|reset-password|subscription_plans|check-email|articles|article_categories)$
            stateless: true
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            entry_point: App\Security\JsonAuthenticationEntryPoint

        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/api/login,              roles: PUBLIC_ACCESS }
        - { path: ^/api/register,           roles: PUBLIC_ACCESS }
        - { path: ^/api/forgot-password,    roles: PUBLIC_ACCESS }
        - { path: ^/api/reset-password,     roles: PUBLIC_ACCESS }
        - { path: ^/api/check-email,        roles: PUBLIC_ACCESS }
        - { path: ^/api/subscription_plans, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/articles,           roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/article_categories,  roles: PUBLIC_ACCESS, methods: [GET] }
        # - { path: ^/api/notifications,       roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api,                    roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
